"""Add Fontsource LXGW WenKai 5.3.0, Light 300 (OFL), as self-hosted glyph shards.
Usage: python3 scripts/build-wenkai.py /path/to/extracted/package
"""
import sys,json,hashlib,shutil
from pathlib import Path
from fontTools.ttLib import TTFont
from fontTools.pens.svgPathPen import SVGPathPen
source=Path(sys.argv[1]);p=source/'files/lxgw-wenkai-latin-300-normal.woff2'
f=TTFont(p);gs=f.getGlyphSet();blocks={};count=0
for code,name in f.getBestCmap().items():
 if code<32 or 127<=code<160:continue
 pen=SVGPathPen(gs,ntos=lambda v:format(round(v,2),'g'));gs[name].draw(pen)
 if not pen.getCommands():continue
 blocks.setdefault(code//128,{})[chr(code)]={'d':pen.getCommands(),'a':f['hmtx'][name][0],'u':f['head'].unitsPerEm};count+=1
out=Path('public/fonts/wenkai');out.mkdir(exist_ok=True)
for b,data in blocks.items():(out/f'{b}.json').write_text(json.dumps(data,ensure_ascii=False,separators=(',',':'))+'\n')
shutil.copyfile(source/'LICENSE','public/fonts/wenkai-OFL.txt')
pth=Path('public/fonts/manifest.json');m=json.loads(pth.read_text());m['fonts']['wenkai']={'glyphCount':count,'blocks':sorted(blocks),'family':'LXGW WenKai','weight':300,'packageVersion':'5.3.0','source':'https://registry.npmjs.org/@fontsource/lxgw-wenkai/-/lxgw-wenkai-5.3.0.tgz','files':[{'file':p.name,'sha256':hashlib.sha256(p.read_bytes()).hexdigest()}]};pth.write_text(json.dumps(m,ensure_ascii=False,indent=2)+'\n')
Path('src/font-coverage.js').write_text('// Generated by font build scripts\nexport const FONT_BLOCKS = '+json.dumps({k:v['blocks'] for k,v in m['fonts'].items()},separators=(',',':'))+';\n')
print(count,len(blocks))
