"""Build self-hosted vector glyph shards from pinned Fontsource Regular WOFF2 files.
Usage: python scripts/build-typefaces.py <source-dir>
Requires fonttools 4.60.2 and brotli 1.2.0. See public/fonts/README.md.
"""
import sys,json,pathlib,re,hashlib,shutil
from fontTools.ttLib import TTFont
from fontTools.pens.svgPathPen import SVGPathPen
source=pathlib.Path(sys.argv[1]);target=pathlib.Path('public/fonts');target.mkdir(exist_ok=True)
manifest={'version':'fontsource-5.3.0','fonts':{}}
for family in ['serif','sans']:
 glyphs={};files=[]
 for path in sorted((source/family).glob('*.woff2')):
  font=TTFont(path);glyphset=font.getGlyphSet();cmap=font.getBestCmap();units=font['head'].unitsPerEm
  files.append({'file':path.name,'sha256':hashlib.sha256(path.read_bytes()).hexdigest()})
  for code,name in cmap.items():
   # Glyphs may be duplicated among language subsets; names are never retained as text.
   if code<32 or 0x7f<=code<0xa0:continue
   pen=SVGPathPen(glyphset,ntos=lambda v:format(round(v,2),'g'))
   glyphset[name].draw(pen);d=pen.getCommands()
   if d:glyphs[chr(code)]={'d':d,'a':font['hmtx'][name][0],'u':units}
  font.close()
 blocks={}
 for c,g in sorted(glyphs.items()):blocks.setdefault(ord(c)//128,{})[c]=g
 out=target/family;out.mkdir(exist_ok=True)
 for block,data in blocks.items():(out/f'{block}.json').write_text(json.dumps(data,ensure_ascii=False,separators=(',',':'))+'\n')
 shutil.copyfile(source/family/'LICENSE',target/f'{family}-OFL.txt')
 manifest['fonts'][family]={'glyphCount':len(glyphs),'blocks':sorted(blocks),'files':files}
 print(f'{family}: {len(glyphs)} glyphs in {len(blocks)} blocks')
(target/'manifest.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+'\n')
pathlib.Path('src/font-coverage.js').write_text('// Generated by scripts/build-typefaces.py\nexport const FONT_BLOCKS = '+json.dumps({k:v['blocks'] for k,v in manifest['fonts'].items()},separators=(',',':'))+';\n')
