import React,{useEffect,useRef,useState} from 'react';
export function statsEnabled(){try{return localStorage.getItem('zitie-stats')!=='off'&&navigator.doNotTrack!=='1'}catch{return false}}
export function track(event){if(!statsEnabled())return;try{fetch('/api/events',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:crypto.randomUUID(),event}),keepalive:true}).catch(()=>{})}catch{}}
export function requestFeedback(query=''){window.dispatchEvent(new CustomEvent('zitie-feedback',{detail:{query}}))}
export default function Feedback(){
 const dialog=useRef(null),ticket=useRef(null);const[open,setOpen]=useState(false),[category,setCategory]=useState('suggestion'),[message,setMessage]=useState(''),[status,setStatus]=useState(''),[busy,setBusy]=useState(false),[enabled,setEnabled]=useState(statsEnabled);
 useEffect(()=>{const show=e=>{if(e.detail?.query){setCategory('request');setMessage(`希望收录：${e.detail.query}`);ticket.current=null}setStatus('');setOpen(true)};window.addEventListener('zitie-feedback',show);return()=>window.removeEventListener('zitie-feedback',show)},[]);
 useEffect(()=>{if(!open)return;dialog.current.showModal();const before=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{dialog.current.close();document.body.style.overflow=before}},[open]);
 async function send(e){e.preventDefault();if(busy)return;setBusy(true);setStatus('');ticket.current??=crypto.randomUUID();try{const r=await fetch('/api/feedback',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:ticket.current,category,message}),signal:AbortSignal.timeout(15000)});const data=await r.json();if(!r.ok)throw Error(data.error||'提交失败，请重试。');setStatus('反馈已收到，谢谢！只有网站维护者可以查看。');setMessage('');ticket.current=null}catch(e){setStatus(e.name==='TimeoutError'?'提交超时，请重试；重复提交不会重复保存。':e.message==='Failed to fetch'?'网络暂不可用，内容已保留，请重试。':e.message)}finally{setBusy(false)}}
 return <section className="feedback-bar"><button type="button" onClick={()=>requestFeedback()}>反馈 / 求收录</button><label><input type="checkbox" checked={enabled} disabled={navigator.doNotTrack==='1'} onChange={e=>{setEnabled(e.target.checked);try{localStorage.setItem('zitie-stats',e.target.checked?'on':'off')}catch{}}}/>允许匿名使用统计</label><small>只统计操作次数，不采集练习正文、搜索词或身份信息。{navigator.doNotTrack==='1'?'已遵循浏览器“不跟踪”设置。':''}</small>
 <dialog ref={dialog} className="library-dialog feedback-dialog" aria-labelledby="feedback-title" onCancel={()=>setOpen(false)} onClose={()=>setOpen(false)}><div className="library-heading"><h2 id="feedback-title">反馈 / 求收录</h2><button type="button" onClick={()=>setOpen(false)}>关闭反馈 ×</button></div><form onSubmit={send}><label>反馈类型<select value={category} disabled={busy} onChange={e=>{setCategory(e.target.value);ticket.current=null}}><option value="request">找不到作品 / 求收录</option><option value="text_error">正文有错</option><option value="layout">排版 / 打印问题</option><option value="suggestion">功能建议</option></select></label><label htmlFor="feedback-message">具体说明</label><textarea id="feedback-message" required minLength={2} maxLength={1500} disabled={busy} value={message} onChange={e=>{setMessage(e.target.value);ticket.current=null;setStatus('')}} placeholder="例如：希望收录的作品名、作者；或出现问题的步骤。"/><p className="source-note">仅发送你在此处填写的内容，不附带练习正文。反馈仅维护者可见，保留 180 天，过期在后续提交时清理；请勿填写个人敏感信息。</p><p role="status">{status}</p><button className="primary" type="submit" disabled={busy||message.trim().length<2}>{busy?'正在提交…':'提交反馈'}</button></form></dialog></section>
}
